import { renderActionButton, renderAlertCard, renderEmptyState, renderPriorityBadge, renderSeverityBadge, renderStatusBadge } from './ui.js';

const safe = (v) => String(v ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

export function renderKpiCard(label = 'Indicateur', value = 0, unit = '') { return `<article class="kpi-card"><p class="kpi-label">${safe(label)}</p><p class="kpi-value">${safe(value)}${unit ? ` <span>${safe(unit)}</span>` : ''}</p></article>`; }
export { renderStatusBadge, renderPriorityBadge, renderSeverityBadge, renderEmptyState, renderActionButton, renderAlertCard };
export function renderProgressBar(label = 'Progression', value = 0, max = 100) { const pct = Math.max(0, Math.min(100, max ? Math.round((Number(value) / Number(max)) * 100) : 0)); return `<article class="chart-card"><p>${safe(label)}</p><div class="progress-bar"><span style="width:${pct}%"></span></div><p>${pct}%</p></article>`; }
export function renderComparisonBars(items = []) { if (!items.length) return renderEmptyState('Aucun graphique disponible pour le moment.'); const max = Math.max(...items.map((i) => Number(i.value || 0)), 1); return `<article class="chart-card comparison-bars">${items.map((i) => `<div><label>${safe(i.label || '')}</label><div class="progress-bar"><span style="width:${Math.round((Number(i.value || 0) / max) * 100)}%"></span></div></div>`).join('')}</article>`; }
export function renderDonutChart(label = 'Performance', value = 0, max = 100) { const pct = Math.max(0, Math.min(100, max ? Math.round((Number(value) / Number(max)) * 100) : 0)); return `<article class="chart-card donut-chart"><svg viewBox="0 0 36 36" aria-label="${safe(label)}"><path d="M18 2.5a15.5 15.5 0 1 1 0 31a15.5 15.5 0 1 1 0-31" stroke="#e2e8f0" stroke-width="3" fill="none"/><path d="M18 2.5a15.5 15.5 0 1 1 0 31a15.5 15.5 0 1 1 0-31" stroke="#1d4ed8" stroke-width="3" fill="none" stroke-dasharray="${pct},100"/></svg><p>${safe(label)} : ${pct}%</p></article>`; }
export function renderMiniBarChart(items = []) { if (!items.length) return renderEmptyState('Aucun graphique disponible pour le moment.'); const max = Math.max(...items.map((i) => Number(i.value || 0)), 1); return `<article class="chart-card mini-bar-chart">${items.map((i) => `<span style="height:${Math.max(8, Math.round((Number(i.value || 0) / max) * 100))}%" title="${safe(i.label || '')}: ${safe(i.value || 0)}"></span>`).join('')}</article>`; }
export function renderTrendLine(points = []) { if (!points.length) return renderEmptyState('Aucun graphique disponible pour le moment.'); const vals = points.map((p) => Number(p || 0)); const max = Math.max(...vals, 1); const step = vals.length > 1 ? 100 / (vals.length - 1) : 100; const poly = vals.map((v, i) => `${(i * step).toFixed(2)},${(100 - ((v / max) * 100)).toFixed(2)}`).join(' '); return `<article class="chart-card"><svg class="trend-line" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline fill="none" stroke="#1d4ed8" stroke-width="2" points="${poly}"/></svg></article>`; }
window.TechnoCharts = { renderKpiCard, renderStatusBadge, renderPriorityBadge, renderSeverityBadge, renderEmptyState, renderActionButton, renderAlertCard, renderProgressBar, renderComparisonBars, renderDonutChart, renderMiniBarChart, renderTrendLine };
